GET http://localhost:3000/api/test

###

POSt http://localhost:3000/api/auth/register
Content-Type: application/json

{
    "user_name":"irfan",
    "email":"irfanprofessor60@gmail.com",
    "password":"irfan"
}



###
GET http://localhost:3000/api/auth/verify?token=0bea2f88a3441385199f0c0666cb5bd66ce3c46175b1fabed054bdd8878dda3f&email=irfanprofessor60@gmail.com
Content-Type: application/json


###
POSt http://localhost:3000/api/auth/verifyUser
Content-Type: application/json

###

POSt http://localhost:3000/api/auth/login
Content-Type: application/json

{
    "email":"test@gmail.com",
    "password":"irfan"
}

###

POSt http://localhost:3000/api/auth/protected
Content-Type: application/json

{}


# "$2b$10$NOahX04rvm1WuBkaNFCIqezYuRgG31k5mGyn3YCfCCyiL1Cvtvfgm"
# "$2b$10$XXpFoJDDwS5cNmm.o.6CDOUNY3mpIAs.DeyXgGkW.8mOjEzdz4jOi"

# eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjo1LCJuYW1lIjoiaXJmYW4iLCJlbWFpbCI6InRlc3RAZ21haWwuY29tIiwicm9sZSI6InNlZWtlciIsImlhdCI6MTc0NTg0NTcwOSwiZXhwIjoxNzQ1ODQ5MzA5fQ.OAjWU7aeg_AukBn0pEIZPQvJ9Sh-OWO6gBHQMubBvDc

# http://http//localhost:3000:/api/auth/verify/37564c8e3be673d69e1dff46602b225343c1f488a7356b042f38d8d34622da75