const express = require('express')
const router = express.Router()
const { verifyToken } = require('../middlewares/verifyTokenMiddleware')
const authorize = require('../middlewares/authorizationMiddleware')
const { insertEmployeeProfile } = require('../routeHandlers/employer_profiles/insertEmployeeProfile')
const { fetchProfile } = require('../routeHandlers/employer_profiles/fetchEmployeeProfile')
const { fetchProfilePercentage } = require('../routeHandlers/employer_profiles/fetchEmployeeProfileCompletionStatus')
const { fetchEmployeeAllJobs } = require('../routeHandlers/employer_profiles/fetchAllPostedJobByEmployee')
const { postJob } = require('../routeHandlers/employer_profiles/insertJob')
const { deleteJob } = require('../routeHandlers/employer_profiles/deleteJobPosting')
const { updateJob } = require('../routeHandlers/employer_profiles/updateJobs')
const { fetchData } = require('../routeHandlers/employer_profiles/fetchApplicantDetails')
const { verifyApplication } = require('../routeHandlers/employer_profiles/verifyApplication')
const { addCompany } = require('../routeHandlers/employer_profiles/addCompany')
const { fetchEmployeeCom } = require('../routeHandlers/employer_profiles/fetchEmployeeCompany')
const { deleteCompany } = require('../routeHandlers/employer_profiles/deleteCompany')
const { updateCompanyProfile } = require('../routeHandlers/employer_profiles/updateCompanyProfile')
const { inviteEmployees } = require('../routeHandlers/employer_profiles/inviteEmployees')
router.use(express.json())

router.post('/insertProfile', verifyToken, authorize(['employee']), insertEmployeeProfile)
router.post('/post/job', verifyToken, authorize(['employee']), postJob)
router.post('/update/job', verifyToken, authorize(['employee']), updateJob)
router.post('/verify/application', verifyToken, authorize(['employee']), verifyApplication)
router.post('/add/company', verifyToken, authorize(['employee']), addCompany)
router.post('/update/company', verifyToken, authorize(['employee']), updateCompanyProfile)
router.post('/check/user/exists/to/invite', verifyToken, authorize(['employee']), inviteEmployees)


router.get('/fetchProfile', verifyToken, authorize(['employee']), fetchProfile)
router.get('/fetchProfilePercentage', verifyToken, authorize(['employee']), fetchProfilePercentage)
router.get('/fetchEmployeeAllJobs', verifyToken, authorize(['employee']), fetchEmployeeAllJobs)
router.get('/fetchApplicantsDetail', verifyToken, authorize(['employee']), fetchData)
router.get('/fetch/employ/company', verifyToken, authorize(['employee']), fetchEmployeeCom)

router.delete('/delete/job', verifyToken, authorize(['employee']), deleteJob)
router.delete('/delete/company', verifyToken, authorize(['employee']), deleteCompany)

module.exports = router 